favicon: null
name: Conception II Hizq
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3438771835062653
  brandStrength: 1
  lightness: 0.2621565100271255
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.6474401322193444
typography_spectrum: 0.692586156539619
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3691756
analytics:
  twitter: null
  google: null
  facebook: null
